# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
cache: packages
addons:
  apt:
    packages:
      - libmpfr-dev
      - ghostscript
r:
  - release
  - devel
r_packages:
  - covr
  - lintr
after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
after_success:
  - Rscript -e 'covr::codecov()'
